"""add_message_evidence_m4_6

Revision ID: 075ce8068be5
Revises: ee5289b10101
Create Date: 2026-08-27 14:30:56.579967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '075ce8068be5'
down_revision: Union[str, Sequence[str], None] = 'ee5289b10101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=255), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_evidence_id'), 'message_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_message_evidence_message_id'), 'message_evidence', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_evidence_message_id'), table_name='message_evidence')
    op.drop_index(op.f('ix_message_evidence_id'), table_name='message_evidence')
    op.drop_table('message_evidence')
    # ### end Alembic commands ###
