"""Add healthcare_facilities table

Revision ID: 7be8859e849e
Revises: bc7b8384c472
Create Date: 2026-08-27 08:44:48.849218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7be8859e849e'
down_revision: Union[str, Sequence[str], None] = 'bc7b8384c472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healthcare_facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('facility_type', sa.String(), nullable=False),
    sa.Column('ownership', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('village', sa.String(), nullable=True),
    sa.Column('taluk', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('emergency_phone', sa.String(), nullable=True),
    sa.Column('services', sa.JSON(), nullable=True),
    sa.Column('emergency_available', sa.Boolean(), nullable=True),
    sa.Column('ambulance_available', sa.Boolean(), nullable=True),
    sa.Column('maternity_available', sa.Boolean(), nullable=True),
    sa.Column('pharmacy_available', sa.Boolean(), nullable=True),
    sa.Column('laboratory_available', sa.Boolean(), nullable=True),
    sa.Column('telemedicine_available', sa.Boolean(), nullable=True),
    sa.Column('opening_hours', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_healthcare_facilities_district'), 'healthcare_facilities', ['district'], unique=False)
    op.create_index(op.f('ix_healthcare_facilities_emergency_available'), 'healthcare_facilities', ['emergency_available'], unique=False)
    op.create_index(op.f('ix_healthcare_facilities_facility_type'), 'healthcare_facilities', ['facility_type'], unique=False)
    op.create_index(op.f('ix_healthcare_facilities_id'), 'healthcare_facilities', ['id'], unique=False)
    op.create_index(op.f('ix_healthcare_facilities_latitude'), 'healthcare_facilities', ['latitude'], unique=False)
    op.create_index(op.f('ix_healthcare_facilities_longitude'), 'healthcare_facilities', ['longitude'], unique=False)
    op.create_index(op.f('ix_healthcare_facilities_name'), 'healthcare_facilities', ['name'], unique=False)
    op.create_index(op.f('ix_healthcare_facilities_pincode'), 'healthcare_facilities', ['pincode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_healthcare_facilities_pincode'), table_name='healthcare_facilities')
    op.drop_index(op.f('ix_healthcare_facilities_name'), table_name='healthcare_facilities')
    op.drop_index(op.f('ix_healthcare_facilities_longitude'), table_name='healthcare_facilities')
    op.drop_index(op.f('ix_healthcare_facilities_latitude'), table_name='healthcare_facilities')
    op.drop_index(op.f('ix_healthcare_facilities_id'), table_name='healthcare_facilities')
    op.drop_index(op.f('ix_healthcare_facilities_facility_type'), table_name='healthcare_facilities')
    op.drop_index(op.f('ix_healthcare_facilities_emergency_available'), table_name='healthcare_facilities')
    op.drop_index(op.f('ix_healthcare_facilities_district'), table_name='healthcare_facilities')
    op.drop_table('healthcare_facilities')
    # ### end Alembic commands ###
