"""add_knowledge_document

Revision ID: a808731789b2
Revises: 06e0bafc2ecf
Create Date: 2026-08-27 09:59:42.518924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a808731789b2'
down_revision: Union[str, Sequence[str], None] = '06e0bafc2ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('publication_date', sa.String(), nullable=True),
    sa.Column('document_version', sa.String(), nullable=True),
    sa.Column('disease_topic', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('authority_level', sa.String(), nullable=True),
    sa.Column('ingestion_timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_disease_topic'), 'knowledge_documents', ['disease_topic'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_document_id'), 'knowledge_documents', ['document_id'], unique=True)
    op.create_index(op.f('ix_knowledge_documents_id'), 'knowledge_documents', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_title'), 'knowledge_documents', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_documents_title'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_document_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_disease_topic'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    # ### end Alembic commands ###
