"""M8.2 Provenance and Versioning

Revision ID: b8793ad7545f
Revises: f7f296a6c029
Create Date: 2026-08-27 18:29:00.989723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8793ad7545f'
down_revision: Union[str, Sequence[str], None] = 'f7f296a6c029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_documents', sa.Column('publisher', sa.String(), nullable=True))
    op.add_column('knowledge_documents', sa.Column('source_url', sa.String(), nullable=True))
    op.add_column('knowledge_documents', sa.Column('publication_date', sa.DateTime(), nullable=True))
    op.add_column('knowledge_documents', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.add_column('knowledge_documents', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('knowledge_documents', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_documents', 'updated_at')
    op.drop_column('knowledge_documents', 'created_at')
    op.drop_column('knowledge_documents', 'verified_at')
    op.drop_column('knowledge_documents', 'publication_date')
    op.drop_column('knowledge_documents', 'source_url')
    op.drop_column('knowledge_documents', 'publisher')
    # ### end Alembic commands ###
