"""update_knowledge_document_m4_1

Revision ID: bc4d4a28dcb2
Revises: a808731789b2
Create Date: 2026-08-27 10:18:29.389426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc4d4a28dcb2'
down_revision: Union[str, Sequence[str], None] = 'a808731789b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_documents', sa.Column('filename', sa.String(), nullable=False))
    op.add_column('knowledge_documents', sa.Column('source_type', sa.String(), nullable=True))
    op.add_column('knowledge_documents', sa.Column('content_hash', sa.String(), nullable=False))
    op.add_column('knowledge_documents', sa.Column('version', sa.String(), nullable=True))
    op.add_column('knowledge_documents', sa.Column('status', sa.String(), nullable=True))
    op.add_column('knowledge_documents', sa.Column('chunk_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_knowledge_documents_content_hash'), 'knowledge_documents', ['content_hash'], unique=False)
    op.drop_column('knowledge_documents', 'publication_date')
    op.drop_column('knowledge_documents', 'document_version')
    op.drop_column('knowledge_documents', 'authority_level')
    op.drop_column('knowledge_documents', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_documents', sa.Column('language', sa.VARCHAR(), nullable=True))
    op.add_column('knowledge_documents', sa.Column('authority_level', sa.VARCHAR(), nullable=True))
    op.add_column('knowledge_documents', sa.Column('document_version', sa.VARCHAR(), nullable=True))
    op.add_column('knowledge_documents', sa.Column('publication_date', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_knowledge_documents_content_hash'), table_name='knowledge_documents')
    op.drop_column('knowledge_documents', 'chunk_count')
    op.drop_column('knowledge_documents', 'status')
    op.drop_column('knowledge_documents', 'version')
    op.drop_column('knowledge_documents', 'content_hash')
    op.drop_column('knowledge_documents', 'source_type')
    op.drop_column('knowledge_documents', 'filename')
    # ### end Alembic commands ###
