"""Update M4.4 Models

Revision ID: ee5289b10101
Revises: b3265006d474
Create Date: 2026-08-27 12:02:38.458676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'ee5289b10101'
down_revision: Union[str, Sequence[str], None] = 'b3265006d474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('messages', sa.Column('risk_level', sa.String(length=50), nullable=True))
    op.add_column('messages', sa.Column('reason_code', sa.String(length=255), nullable=True))
    op.drop_column('messages', 'metadata')
    op.add_column('patient_contexts', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('patient_contexts', sa.Column('sex', sa.String(length=20), nullable=True))
    op.add_column('patient_contexts', sa.Column('relevant_notes', sa.Text(), nullable=True))
    op.add_column('patient_contexts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('patient_contexts', 'emergency_notes')
    op.drop_column('patient_contexts', 'preferred_language')
    op.drop_column('patient_contexts', 'age_group')
    op.drop_column('patient_contexts', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_contexts', sa.Column('location', sa.VARCHAR(length=255), nullable=True))
    op.add_column('patient_contexts', sa.Column('age_group', sa.VARCHAR(length=50), nullable=True))
    op.add_column('patient_contexts', sa.Column('preferred_language', sa.VARCHAR(length=10), nullable=True))
    op.add_column('patient_contexts', sa.Column('emergency_notes', sa.TEXT(), nullable=True))
    op.drop_column('patient_contexts', 'created_at')
    op.drop_column('patient_contexts', 'relevant_notes')
    op.drop_column('patient_contexts', 'sex')
    op.drop_column('patient_contexts', 'age')
    op.add_column('messages', sa.Column('metadata', sqlite.JSON(), nullable=True))
    op.drop_column('messages', 'reason_code')
    op.drop_column('messages', 'risk_level')
    op.drop_column('messages', 'language')
    # ### end Alembic commands ###
