"""M8.1 Authoritative Docs

Revision ID: f7f296a6c029
Revises: 123abc456def
Create Date: 2026-08-27 16:33:56.752434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7f296a6c029'
down_revision: Union[str, Sequence[str], None] = '123abc456def'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_documents', sa.Column('is_authoritative', sa.Boolean(), nullable=False))
    op.add_column('knowledge_documents', sa.Column('verification_status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_documents', 'verification_status')
    op.drop_column('knowledge_documents', 'is_authoritative')
    # ### end Alembic commands ###
