from typing import TypedDict, List, Dict, Any, Optional

class AgentState(TypedDict):
    # The user's input query
    query: str
    
    # The language of the query (e.g., 'en', 'hi', 'ta', 'mr')
    language: str
    
    # Recent conversation history
    chat_history: List[Dict[str, str]]
    
    # Minimal patient context string
    patient_context: str
    
    # The type of query identified by the Triage Agent (e.g., 'medical', 'greeting', 'emergency')
    query_type: Optional[str]
    
    # Retrieved documents from the Hybrid Retriever
    retrieved_docs: List[Dict[str, Any]]
    
    # The final answer generated by the QA Agent
    final_answer: Optional[str]
    
    # Explainable AI: The sources used to generate the answer (legacy)
    sources: List[Dict[str, Any]]
    
    # Explainable AI: Structured evidence for M4.5
    evidence: List[Dict[str, Any]]
    
    # Flag to determine if the query is an emergency
    is_emergency: bool
    
    # Structured triage result
    triage: Optional[Dict[str, Any]]
    
    # Risk level (GREEN, YELLOW, ORANGE, RED)
    risk_level: Optional[str]
    
    # Latency tracking for Observability
    triage_latency_ms: Optional[float]
    retrieval_latency_ms: Optional[float]
    generation_latency_ms: Optional[float]
