from typing import TypedDict, List, Dict, Any, Optional

class AgentState(TypedDict):
    # The user's input query
    query: str
    
    # The type of query identified by the Triage Agent (e.g., 'medical', 'greeting', 'emergency')
    query_type: Optional[str]
    
    # Retrieved documents from the Hybrid Retriever
    retrieved_docs: List[Dict[str, Any]]
    
    # The final answer generated by the QA Agent
    final_answer: Optional[str]
    
    # Explainable AI: The sources used to generate the answer
    sources: List[Dict[str, Any]]
    
    # Flag to determine if the query is an emergency
    is_emergency: bool
